import React from "react";

import { getServerSession } from "next-auth";
import { SessionProvider } from "../components/SessionProvider";
import SideBar from "../components/SideBar";
import "../styles/globals.css";
import { authOptions } from "../pages/api/auth/[...nextauth]";
import Login from "../components/Login";
import { signOut } from "next-auth/react";
import ClientProvider from "../components/ClientProvider";

export const metadata = {
  title: "ChatGPT 2.0",
  description: "Generated by Next.js",
};

// server components can be asynchronous functions.. client components cannot be

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className="flex">
              <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
                <SideBar />
              </div>
              <ClientProvider />

              <div className="bg-[#343541] flex-1 ">{children}</div>
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
